### ISSUE TITLE
Crash with Fabric Server - netherite-plus-mod-beta-1.5.0

### ISSUE THREAD

**Issue by shikyo13** [OroArmor/Netherite-Plus-Mod#20]
Crashes on Fabric Server
Works on Fabric Client with same modlist
No crash report generated, latest.log below

fabric loader 0.9.0 build 204
netherite-plus-mod-beta-1.5.0
fabric-api-0.16.2+build.385

[12:22:59] [main/INFO]: Loading for game Minecraft 1.16.1
[12:22:59] [main/WARN]: Warnings were found! 
 - Mod beenfo recommends mod {modmenu @ [*]}, which is missing!
 - Mod beenfo recommends mod {modupdater @ [>=1.1.7]}, which is missing!
 - Conflicting versions found for fabric-api-base: used 0.1.3+12a8474c7c, also found 0.1.3+12a8474c02
[12:22:59] [main/WARN]: Mod `lightoverlay` (5.4.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[12:22:59] [main/WARN]: Mod `harvest` (1.2.12) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[12:22:59] [main/INFO]: [FabricLoader] Loading 128 mods: fabric-keybindings-v0@0.2.0+3fa9f7c502, fabricloader@0.9.0+build.204, trinkets@2.6.3, com_fasterxml_jackson_core_jackson-annotations@2.9.0, beenfo@1.16-fabric0.13.1-1.1, org_javacord_javacord-api@3.0.6, sleepvote@${version}, bbor@2.3-1.16.1, org_javacord_javacord-core@3.0.6, fabric-dimensions-v1@1.0.0+a71b305302, kibe@1.1.11-BETA, libgamerule@${version}, com_squareup_okio_okio@1.13.0, cotton-client-commands@1.0.1+1.16-rc1, fabric-game-rule-api-v1@1.0.0+fe81e12502, fabric-api-base@0.1.3+12a8474c7c, controlling@1.1.2, xaeroworldmap@1.8.0, jumpoverfences@1.16-0.0.3, tweakeroo@0.10.0-dev.20200630.023405, randompatches@1.16.1-0.0.0.5-fabric, roughlyenoughresources@2.0.2, org_jetbrains_kotlin_kotlin-stdlib@1.3.72, waila@1.9.22, playerabilitylib@1.2.0, com_neovisionaries_nv-websocket-client@2.6, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.3.72, chatemotes@1.1, fabric@0.16.2+build.385-1.16.1, netherite_plus@beta-1.5.0, anvil_fix@1.1.3+build.7-1.16, fabric-networking-v0@0.1.10+e00ecb5f02, cleancut@mc1.16-2.1-fabric, fabric-screen-handler-api-v1@1.1.0+97324d1102, com_github_therandomlabs_trlutils-config@master-SNAPSHOT, simpledrawers@1.8.0-1.16.1, blockshifter@1.0.2, com_squareup_okhttp3_logging-interceptor@3.9.1, tacocraft@1.3.1+mc.1.16, phosphor@0.6.0+build.7, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.3.72, fabric-tool-attribute-api-v1@1.2.0+55e0cc5f02, cloth-client-events-v0@1.0.4, fabric-biomes-v1@0.2.7+059ea86602, fabric-events-interaction-v0@0.3.3+7066030f02, fabric-crash-report-info-v1@0.1.2+b7f9825d02, fabric-language-kotlin@1.3.72+build.1, infinityfix@1.1.0, fabric-key-binding-api-v1@1.0.1+f404f3be02, fabric-language-scala@0.3.2.12, cloth-config2@4.6.0, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.7, fabric-resource-loader-v0@0.2.6+f41e209802, malilib@0.10.0-dev.21+arne.1, org_jetbrains_kotlin_kotlin-reflect@1.3.72, worldedit@7.2.0-beta-02+d10d7d6, cardinal-components-entity@2.4.0-nightly.1.16-rc1.build.2, staticdata@1.1.2, magna@1.1.4-1.16.1, fabric-commands-v0@0.2.0+52d3083602, fabric-registry-sync-v0@0.3.8+7dba2d6c02, cardinal-components-base@2.4.0-nightly.1.16-rc1.build.2, lightoverlay@5.4.0, com_squareup_okhttp3_okhttp@3.9.1, fabric-mining-levels-v0@0.1.2+b764ce9902, fabric-item-groups-v0@0.2.0+438f963602, fabric-models-v0@0.1.0+dfdb52d602, shulkerboxtooltip@2.1.0+1.16.1, fdlink@0.4.2, org_jetbrains_annotations@17.0.0, fabric-renderer-api-v1@0.2.13+eae12eb802, parchment@1.0.2+1.15.2, inventorysorter@1.7.0-1.16, libcd@2.5.0+1.16.1, org_jetbrains_kotlinx_kotlinx-coroutines-core@1.3.7, vanilla-hammers@2.0.2-1.16.1, easierenchanting@1.2.0, fabric-containers-v0@0.1.8+045df74f02, lithium@0.5.1, fabric-object-builder-api-v1@1.5.6+a2d21ddd02, portalcrafter@1.0.0, leadvillagers@2.1.0+mc1.16.1, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-textures-v0@1.0.4+eae12eb802, com_electronwill_night-config_core@3.6.0, fabric-rendering-fluids-v1@0.1.8+b7084faa02, com_fasterxml_jackson_core_jackson-databind@2.9.3, fabric-lifecycle-events-v1@1.2.0+e83e061c02, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, com_github_therandomlabs_trlutils-fabric@1.16-SNAPSHOT, fabric-loot-tables-v1@1.0.0+386eb69e02, com_vdurmont_emoji-java@5.1.1, com_fasterxml_jackson_core_jackson-core@2.9.3, carpet@1.4.0, fabric-particles-v1@0.2.1+0a6f2a7002, minecraft@1.16.1, gottaclimbfast@1.0, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, fabric-command-api-v1@1.0.8+5ce5339802, cloth-basic-math@0.5.1, jankson@3.0.0+j1.2.0, wands@1.1, fabric-renderer-indigo@0.3.4+34d6c87102, mixedslab@1.16.1-fabric-1.1.0.1, com_electronwill_night-config_toml@3.6.0, fabric-item-api-v1@1.0.0+16acbe5b02, roughlyenoughitems@4.10.3, kyrptconfig@1.0.4-1.16, libgui@2.1.1+1.16.1, xaerominimap@20.18.0, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, autoconfig1u@3.2.0-unstable, harvest@1.2.12, fabric-content-registries-v0@0.1.9+059ea86602, org_json_json@20170516, screenshotclipboard@1.0.5, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, blue_endless_jankson@+, gravestones@1.4.0, appleskin@1.0.11, itemscroller@0.15.0-dev.20200630.022843, coalnugget@1.2.0.4, org_apache_logging_log4j_log4j-api@2.11.0, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, vanillaautomated@1.1.2, fabric-object-builders-v0@0.6.1+a2d21ddd02
[12:22:59] [main/WARN]: Mod `sleepvote` (${version}) does not respect SemVer - comparison support is limited.
[12:22:59] [main/WARN]: Mod `libgamerule` (${version}) does not respect SemVer - comparison support is limited.
[12:22:59] [main/WARN]: Mod `netherite_plus` (beta-1.5.0) does not respect SemVer - comparison support is limited.
[12:22:59] [main/WARN]: Mod `cleancut` (mc1.16-2.1-fabric) does not respect SemVer - comparison support is limited.
[12:22:59] [main/WARN]: Mod `com_github_therandomlabs_trlutils-config` (master-SNAPSHOT) does not respect SemVer - comparison support is limited.
[12:22:59] [main/WARN]: Mod `fabric-language-scala` (0.3.2.12) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[12:22:59] [main/WARN]: Mod `blue_endless_jankson` (+) does not respect SemVer - comparison support is limited.
[12:22:59] [main/WARN]: Mod `coalnugget` (1.2.0.4) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[12:23:00] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/shiky/Desktop/1.16.1/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[12:23:02] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
[12:23:02] [main/WARN]: Error loading class: net/minecraft/class_746 (java.lang.ClassNotFoundException: net/minecraft/class_746)
[12:23:02] [main/WARN]: @Mixin target net.minecraft.class_746 was not found trinkets.mixins.json:ClientPlayerEntityMixin
[12:23:05] [main/WARN]: Error loading class: fi/dy/masa/malilib/config/options/ConfigDouble (java.lang.ClassNotFoundException: fi/dy/masa/malilib/config/options/ConfigDouble)

**Comment by OroArmor** [comment]
You are missing malilib

**Comment by shikyo13** [comment]
malilib-fabric-1.16.1-0.10.0-dev.21+arne.1.jar

is part of my modlist
I have Tweakeroo and Litematica which also requite malilib

**Comment by OroArmor** [comment]
Weird. This might be an issue on my part, but everything seems in order

**Comment by shikyo13** [comment]
Tried loading up a server with just this, malilib, and fabric api.


[12:56:01] [main/INFO]: Loading for game Minecraft 1.16.1
[12:56:02] [main/INFO]: [FabricLoader] Loading 43 mods: fabric-screen-handler-api-v1@1.1.0+97324d1102, minecraft@1.16.1, fabric-renderer-api-v1@0.2.13+eae12eb802, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, fabric-keybindings-v0@0.2.0+3fa9f7c502, fabric-command-api-v1@1.0.8+5ce5339802, fabricloader@0.9.0+build.204, fabric-tool-attribute-api-v1@1.2.0+55e0cc5f02, fabric-renderer-indigo@0.3.4+34d6c87102, fabric-containers-v0@0.1.8+045df74f02, fabric-object-builder-api-v1@1.5.6+a2d21ddd02, fabric-dimensions-v1@1.0.0+a71b305302, fabric-biomes-v1@0.2.7+059ea86602, fabric-item-api-v1@1.0.0+16acbe5b02, fabric-crash-report-info-v1@0.1.2+b7f9825d02, fabric-events-interaction-v0@0.3.3+7066030f02, fabric-game-rule-api-v1@1.0.0+fe81e12502, fabric-api-base@0.1.3+12a8474c02, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, fabric-key-binding-api-v1@1.0.1+f404f3be02, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-resource-loader-v0@0.2.6+f41e209802, malilib@0.10.0-dev.21+arne.1, fabric-textures-v0@1.0.4+eae12eb802, fabric-content-registries-v0@0.1.9+059ea86602, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, fabric-rendering-fluids-v1@0.1.8+b7084faa02, fabric-registry-sync-v0@0.3.8+7dba2d6c02, fabric-commands-v0@0.2.0+52d3083602, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, fabric-lifecycle-events-v1@1.2.0+e83e061c02, fabric-mining-levels-v0@0.1.2+b764ce9902, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, fabric-loot-tables-v1@1.0.0+386eb69e02, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, fabric@0.16.2+build.385-1.16.1, netherite_plus@beta-1.5.0, fabric-particles-v1@0.2.1+0a6f2a7002, fabric-models-v0@0.1.0+dfdb52d602, fabric-item-groups-v0@0.2.0+438f963602, fabric-object-builders-v0@0.6.1+a2d21ddd02, fabric-networking-v0@0.1.10+e00ecb5f02
[12:56:02] [main/WARN]: Mod `netherite_plus` (beta-1.5.0) does not respect SemVer - comparison support is limited.
[12:56:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/shiky/Desktop/1.16.1/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[12:56:06] [main/WARN]: Error loading class: fi/dy/masa/malilib/config/options/ConfigDouble (java.lang.ClassNotFoundException: fi/dy/masa/malilib/config/options/ConfigDouble)

![image](https://user-images.githubusercontent.com/10563401/88957294-49816200-d264-11ea-825b-66e5fc3e2a70.png)

**Comment by OroArmor** [comment]
Yeah same issue. I'll see if I can fix it soon.

**Comment by shikyo13** [comment]
Ok, just wanted to help out and I'm excited to play with the mod! Thanks!

**Comment by rxay579** [comment]
Looks like it's still failing with NP v1.6.0.

Logs from NP v1.6.0 on dedicated server (Fabric, NP, Malilib,Trinkets):

When first launching, the server launch fails and doesn't generate config files.
[latest - no configs.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5012978/latest.-.no.configs.log)

Server launch still fails after manually copying configs from a working test client.
[latest - manual configs.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5012982/latest.-.manual.configs.log)

Config files used, generated after deleting existing config folder contents:
[config.zip](https://github.com/OroArmor/Netherite-Plus-Mod/files/5012998/config.zip)

**Comment by OroArmor** [comment]
um great. So two things. 1. you dont need malilib anymore, i forgot to remove that, 2. ```java.lang.NoClassDefFoundError: net/minecraft/class_742``` is the isse, which i dont know how to fix. What version of the fabric launcher do you have?

**Comment by rxay579** [comment]
Pretty sure it's 0.9.0.  Logs say "fabricloader@0.9.0+build.204".  Usually test using Minecraft's bundled JRE (v1.8.0u51x64).

Log from a fresh server instance with Fabric API, NP, Trinkets.  JRE is v1.8.0u231x64.  Looks like the same error.
[latest - fresh.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5013087/latest.-.fresh.log)
fabric-api-0.16.2+build.385-1.16.1.jar
netherite-plus-mod-beta-1.6.0.jar
trinkets-2.6.3.jar

No config files generated, so it seems like it's failing before that stage.

**Comment by OroArmor** [comment]
ok think i fixed it

**Comment by OroArmor** [comment]
Try this. extract it
[netherite-plus-mod-beta-1.6.1.zip](https://github.com/OroArmor/Netherite-Plus-Mod/files/5013148/netherite-plus-mod-beta-1.6.1.zip)

**Comment by OroArmor** [comment]
also the configs are generated when the world closes, i should fix it to generate if the file doesnt exist, just dont have that in yet

**Comment by rxay579** [comment]
Still crashes on server, new logs:

NP 1.6.1 w/ JRE 8u231
[latest - 1.6.1 jre8u231.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5013225/latest.-.1.6.1.jre8u231.log)

NP 1.6.1 w/ JRE 8u51 (Minecraft's native JRE)
[latest - 1.6.1 jre8u51.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5013226/latest.-.1.6.1.jre8u51.log)

**Comment by OroArmor** [comment]
Yes. ok i fixed part of it

**Comment by OroArmor** [comment]
try this now. Sorry you are, but it works fine on my end
[netherite-plus-mod-beta-1.6.1.zip](https://github.com/OroArmor/Netherite-Plus-Mod/files/5013255/netherite-plus-mod-beta-1.6.1.zip)

**Comment by OroArmor** [comment]
oops i figured out why it wasnt working on my end. works completely now

**Comment by rxay579** [comment]
:) Was about to say that the last version worked, but with an error in the server log.
[latest - server.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5013278/latest.-.server.log)
[latest - client.log](https://github.com/OroArmor/Netherite-Plus-Mod/files/5013279/latest.-.client.log)

**Comment by OroArmor** [comment]
i dont see any errors...

There is the issue with trinkets, but thats not under my control: `Error loading class: net/minecraft/class_746 (java.lang.ClassNotFoundException: net/minecraft/class_746)`

**Comment by rxay579** [comment]
Ah, sorry, warning.  Thanks so much.

**Comment by OroArmor** [comment]
cool. thanks for helping me so much!
